[tools]
bun = "latest"
erlang = "latest"
elixir = "latest"
node = "22.21.1"
perl = "5.42.0"
pnpm = "10.13.1"
python = "3.11.11"
clang-format = "latest"
git-lfs = "latest"
uv = "latest"
ruby = "3.4.9"
fzf = "latest"
ripgrep = "latest"
fd = "latest"
lazygit = "latest"
tmux = "latest"
yq = "latest"
jq = "latest"
gh = "latest"
yt-dlp = "latest"
yamlfmt = "latest"
neovim = "latest"
docker-cli = "latest"
docker-compose = "latest"
imagemagick = "latest"
opencode = "latest"
codex = "latest"
claude = "latest"
"npm:portless" = "latest"
"npm:agent-browser" = "latest"
"npm:repomix" = "latest"
"npm:vercel" = "latest"
"npm:turbo" = "latest"
"npm:@yaakapp/cli" = "latest"
"npm:tree-sitter-cli" = "latest"

[settings]
experimental = false

[settings.npm]
package_manager = "bun"
