[tools]
node = "24.14.1"
perl = "5.42.0"
python = "3.14.5"
ruby = "3.4.9"
ccache = "latest"
age = "latest"
cocoapods = "latest"
coreutils = "latest"
direnv = "latest"
bun = "1.3.14"
pnpm = "latest"
git-lfs = "latest"
uv = "latest"
fastfetch = "latest"
xcodes = "latest"
fzf = "latest"
ripgrep = "latest"
fd = "latest"
lazygit = "latest"
tmux = "latest"
yq = "latest"
jq = "latest"
gh = "latest"
awscli = "latest"
gcloud = "latest"
flyctl = "latest"
cloudflared = "latest"
mkcert = "latest"
hub = "latest"
act = "latest"
cmake = "latest"
rust = "latest"
ollama = "latest"
redis = "latest"
ffmpeg = "latest"
yt-dlp = "latest"
bat = "latest"
eza = "latest"
zoxide = "latest"
pandoc = "latest"
typst = "latest"
yamlfmt = "latest"
neovim = "latest"
docker-cli = "latest"
docker-compose = "latest"
imagemagick = "latest"
opencode = "latest"
codex = "latest"
claude = "latest"
pi = "latest"
infisical = "latest"
portless = "latest"
vercel = "latest"
turbo = "latest"
worktrunk = "latest"
"npm:ctx7" = "latest"
"npm:eas-cli" = "latest"
"npm:agent-device" = "latest"
"npm:agent-browser" = "latest"
"npm:repomix" = "latest"
"npm:sfw" = "latest"
"npm:@yaakapp/cli" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:cursor-agent" = "latest"
"npm:@typescript/native-preview" = "latest"
"github:ryanoasis/nerd-fonts" = { version = "latest", asset_pattern = "Hack.zip" }
mas = "latest"
"gem:fastlane" = "latest"
"pipx:httpie" = "latest"
"pipx:mackup" = "latest"
"npm:ios-deploy" = "latest"
"github:boyter/scc" = "latest"
"github:AlDanial/cloc" = "latest"
"github:OpenVPN/easy-rsa" = "latest"
"pipx:tldr" = "latest"
"conda:aria2" = "latest"
"conda:bfg" = "latest"
"conda:ghostscript" = "latest"
"conda:sox" = "latest"
"conda:tig" = "latest"
"conda:tree" = "latest"
"conda:wget" = "latest"

[settings]
experimental = true

[settings.npm]
package_manager = "bun"
